name: Auto Tag

on:
  issues:
    types:
      - reopened
      - closed
  pull_request:
    types:
      - closed
  release:

jobs:

  auto-tag:
    name: Auto tag issues and PRs
    uses: graasp/graasp-deploy/.github/workflows/auto-tag.yml@185-create-re-usable-auto-tag-workflow
