name: Tag closed issues as un-released

on:
  issues:
    types: [closed]

jobs:
  tag-closed-issues:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.state_reason == 'completed' }}
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh issue edit ${{ github.event.issue.number }} --add-label un-released --repo ${{ github.event.repository.full_name }}
      - run: echo '# Issue was closed and has been tagged as `un-released`' >> $GITHUB_STEP_SUMMARY
