name: Tag closed issues as un-released

on:
  issues:
    types: [closed]

jobs:
  tag-closed-issues:
    runs-on: ubuntu-latest
    steps:
      - run: jq ${{ github.event }}
      - run: gh issue edit ${{ github.event.number }} --add-label un-released
      - run: echo '# Issue was closed and has been tagged as `un-released`' >> $GITHUB_STEP_SUMMARY
        if: ${{ github.event.state_reason == 'completed' }}
