name: Tag merged PRs as un-released

on:
  pull_request:
    types: [closed]

jobs:
  tag-pr-when-merged:
    runs-on: ubuntu-latest
    if: ${{ github.event.merged == true }}
    steps:
      - run: echo ${{ github.event }}
      - run: gh pr edit ${{ github.event.number }} --add-label un-released
      - run: echo '# PR was merged and has been tagged as `un-released`' >> $GITHUB_STEP_SUMMARY
