name: Tag closed issues as un-released

on:
  issues:
    types: [closed]

jobs:
  tag-closed-issues:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.state_reason == 'completed' }}
    env:
      LABEL_NAME: un-released
      REPO: ${{ github.event.repository.full_name }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}

    steps:

      - name: Get `${{ env.LABEL_NAME }}` label
        id: label-list
        run: echo label=$(gh label list --search $LABEL_NAME -L 1 --json name -q '.[].name' --repo $REPO) >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create label if does not exist
        if: ${{ steps.label-list.outputs.label != env.LABEL_NAME }}
        run: |
          gh label create $LABEL_NAME --color e3fce3 --repo $REPO;
          echo ':neckbeard: Created the `${{ env.LABEL_NAME }}` label !' >> $GITHUB_STEP_SUMMARY;
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Tag Issue
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label $LABEL_NAME --repo ${{ github.event.repository.full_name }};
          echo ':label: Issue #`${{ env.ISSUE_NUMBER }}` has been tagged as `${{ env.LABEL_NAME }}`' >> $GITHUB_STEP_SUMMARY;

        env:
          GITHUB_TOKEN: ${{ github.token }}
