name: Tag closed issues as un-released

on:
  issues:
    types: [closed]

jobs:
  tag-closed-issues:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.state_reason == 'completed' }}
    env:
      REPO: ${{ github.event.repository.full_name }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}

    steps:

      - name: Get `un-released` label
        id: label-list
        run: echo label=$(gh label list --search un-released --repo $REPO) >> GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create label if does not exist
        if: ${{ steps.label-list.outputs.label == '' }}
        run: |
          gh label create un-released --color e3fce3 --repo $REPO;
          echo ':neckbeard: Created the `un-released` label !' >> $GITHUB_STEP_SUMMARY;
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Tag Issue
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label un-released --repo ${{ github.event.repository.full_name }};
          echo ':label: Issue #`$ISSUE_NUMBER` has been tagged as `un-released`' >> $GITHUB_STEP_SUMMARY;

        env:
          GITHUB_TOKEN: ${{ github.token }}
